Repository INF2-2019/servidor, pull requests merged in 2019-10, with the labels that each got.

#1 Estruturação do servidor
  app/src/java/controller/biblioteca/.delete
  app/src/java/controller/diario/.delete
  app/src/java/model/biblioteca/.delete
  app/src/java/model/diario/.delete
  app/src/java/services/ConnectionFactory.java
  app/src/java/view/biblioteca/.delete
  app/src/java/view/diario/.delete
Labels: enhancement

#5 Mudando a estruturacao
  app/src/java/repository/biblioteca/.delete
  app/src/java/repository/diario/.delete
  app/src/java/utils/ConnectionFactory.java
Labels: enhancement

#6 Corrigir URL do servidor
  app/src/java/utils/ConnectionFactory.java
Labels: bug

#7 Corrigir pacote de ConnectionFactory
  app/src/java/utils/ConnectionFactory.java
Labels: bug

#8 Estrutura de cursos: operação de busca
  app/.idea/misc.xml
  app/src/java/controller/diario/.delete
  app/src/java/controller/diario/cursos/Atualizar.java
  app/src/java/controller/diario/cursos/Consultar.java
  app/src/java/controller/diario/cursos/Deletar.java
  app/src/java/controller/diario/cursos/Inserir.java
  app/src/java/model/diario/.delete
  app/src/java/model/diario/curso/Curso.java
  app/src/java/repository/diario/.delete
  app/src/java/repository/diario/CursoRepository.java
  app/src/java/utils/ConnectionFactory.java
  app/src/java/view/diario/curso/CursoView.java
Labels: enhancement

#16 Manutenção de departamentos
  app/nbproject/ant-deploy.xml
  app/nbproject/project.properties
  app/src/java/controller/diario/departamentos/AtualizarDepartamento.java
  app/src/java/controller/diario/departamentos/ConsultarDepartamentos.java
  app/src/java/controller/diario/departamentos/InserirDepartamento.java
  app/src/java/controller/diario/departamentos/RemoverDepartamento.java
  app/src/java/model/diario/DepartamentoModel.java
  app/src/java/repository/diario/DepartamentoRepository.java
  app/src/java/views/diario/departamentos/DepartamentoView.java
Labels: enhancement

#22 Manutenção de departamentos
  app/nbproject/ant-deploy.xml
  app/nbproject/project.properties
  app/src/java/diario/.delete
  app/src/java/diario/departamentos/controller/Atualiza.java
  app/src/java/diario/departamentos/controller/Consulta.java
  app/src/java/diario/departamentos/controller/Insere.java
  app/src/java/diario/departamentos/controller/Remove.java
  app/src/java/diario/departamentos/model/Departamento.java
  app/src/java/diario/departamentos/view/View.java
Labels: enhancement

#24 Manutenção de cursos
  app/src/java/diario/cursos/controllers/AtualizarCursos.java
  app/src/java/diario/cursos/controllers/ConsultarCursos.java
  app/src/java/diario/cursos/controllers/DeletarCursos.java
  app/src/java/diario/cursos/controllers/InserirCursos.java
  app/src/java/diario/cursos/models/CursoModel.java
  app/src/java/diario/cursos/models/Model.java
  app/src/java/diario/cursos/repository/CursoRepository.java
  app/src/java/diario/cursos/view/CursoConsultaView.java
  app/src/java/diario/cursos/view/ErroView.java
  app/src/java/diario/cursos/view/RenderException.java
  app/src/java/diario/cursos/view/SucessoView.java
  app/src/java/diario/cursos/view/View.java
  app/src/java/utils/ConnectionFactory.java
  app/src/java/utils/Conversores.java
  app/web/WEB-INF/glassfish-web.xml
Labels: enhancement

#30 Finalizado documentação para a funcionalidade de manipulação de c…
  docs/estrutura/biblioteca/.delete
  docs/estrutura/diario/cursos.md
Labels: documentation

#33 Manutenção de Etapas
  app/src/java/diario/etapas/Model.java
  app/src/java/diario/etapas/RenderException.java
  app/src/java/diario/etapas/controller/AtualizarEtapas.java
  app/src/java/diario/etapas/controller/ConsultarEtapas.java
  app/src/java/diario/etapas/controller/DeletarEtapas.java
  app/src/java/diario/etapas/controller/InserirEtapas.java
  app/src/java/diario/etapas/model/EtapasModel.java
  app/src/java/diario/etapas/repository/EtapasRepository.java
  app/src/java/diario/etapas/view/ErroFormatView.java
  app/src/java/diario/etapas/view/ErroSemParametroView.java
  app/src/java/diario/etapas/view/ErroSqlView.java
  app/src/java/diario/etapas/view/EtapasConsultaView.java
  app/src/java/diario/etapas/view/SucessoView.java
  app/src/java/diario/etapas/view/View.java
  docs/estrutura/diario/etapas.md
Labels: enhancement

#38 Correção e melhoria de erros (XML) e adição de autenticação para…
  app/src/java/diario/cursos/controllers/AtualizarCursos.java
  app/src/java/diario/cursos/controllers/ConsultarCursos.java
  app/src/java/diario/cursos/controllers/DeletarCursos.java
  app/src/java/diario/cursos/controllers/InserirCursos.java
  app/src/java/diario/cursos/repository/CursoRepository.java
  app/src/java/diario/cursos/view/ErroView.java
  app/src/java/diario/cursos/view/ExcecaoTurmaVinculada.java
Labels: enhancement

#45 Aperfeiçoamento da manutenção de departamentos no servidor
  app/nbproject/project.properties
  app/src/java/diario/departamentos/controller/Atualiza.java
  app/src/java/diario/departamentos/controller/Consulta.java
  app/src/java/diario/departamentos/controller/Insere.java
  app/src/java/diario/departamentos/controller/Remove.java
  app/src/java/diario/departamentos/repository/DepartamentoRepository.java
  app/src/java/diario/departamentos/view/ConsultaView.java
  app/src/java/diario/departamentos/view/ErroView.java
  app/src/java/diario/departamentos/view/SucessoView.java
  app/src/java/diario/departamentos/view/View.java
Labels: enhancement
