Repository INF2-2019/servidor, pull requests merged in 2019-11, with the labels that each got.

#56 Correção sessão
  app/web/WEB-INF/web.xml
Labels: bug

#55 Transferência de aluno
  app/src/java/diario/transferencia/controller/ParametrosIncorretosException.java
  app/src/java/diario/transferencia/controller/Transfere.java
  app/src/java/diario/transferencia/repository/AlunoInativoException.java
  app/src/java/diario/transferencia/repository/TransfereRepository.java
  app/src/java/diario/transferencia/view/ErroView.java
  app/src/java/diario/transferencia/view/RenderException.java
  app/src/java/diario/transferencia/view/SucessoView.java
  app/src/java/diario/transferencia/view/View.java
  db/mysql 5.6-/diario.sql
  db/mysql 5.7+/diario.sql
Labels: enhancement

#52 Login dos professores
  app/src/java/diario/professores/AtualizarProfessor.java
  app/src/java/diario/professores/ConsultarProfessor.java
  app/src/java/diario/professores/ExcecaoParametrosIncorretos.java
  app/src/java/diario/professores/InsercaoProfessor.java
  app/src/java/diario/professores/LogarProfessor.java
  app/src/java/diario/professores/NotAuthorizedException.java
  app/src/java/diario/professores/RemoverProfessor.java
  app/src/java/diario/professores/Validacao.java
  docs/estrutura/diario/professores.md
Labels: enhancement

#61 Corrigir status para parâmetros incorretos
  app/src/java/diario/transferencia/controller/Transfere.java
Labels: bug

#68 Manutenção de alunos
  app/src/java/diario/alunos/repository/AlunosRepository.java
  app/src/java/diario/alunos/servlets/AlterarAlunos.java
  app/src/java/diario/alunos/servlets/AlterarFoto.java
  app/src/java/diario/alunos/servlets/AlterarSenha.java
  app/src/java/diario/alunos/servlets/ConsultarPorId.java
  app/src/java/diario/alunos/servlets/DeletarAlunos.java
  app/src/java/diario/alunos/servlets/InserirAlunos.java
  app/src/java/diario/alunos/servlets/ListarAlunos.java
  app/src/java/diario/alunos/servlets/LogarAluno.java
  app/src/java/diario/campi/repository/CampiRepository.java
  app/src/java/diario/campi/servlets/AlterarCampi.java
  app/src/java/diario/campi/servlets/DeletarCampi.java
  app/src/java/diario/campi/servlets/InserirCampi.java
  app/src/java/diario/campi/view/viewConsulta.java
  app/src/java/utils/autenticador/DiarioAutenticador.java
Labels: enhancement

#73 Mensagem de falha de autenticação
  app/src/java/diario/transferencia/controller/AutenticacaoException.java
  app/src/java/diario/transferencia/controller/Transfere.java
Labels: fix

#69 Listagem Acervo Novamente
  .gitignore
  app/src/java/biblioteca/acervo/AtualizarAcervo.java
  app/src/java/biblioteca/acervo/ConsultarAcervo.java
  app/src/java/biblioteca/acervo/DeletarAcervo.java
  app/src/java/biblioteca/acervo/EmailHelper.java
  app/src/java/biblioteca/acervo/ExcecaoNaoAutorizado.java
  app/src/java/biblioteca/acervo/ExcecaoParametrosIncorretos.java
  app/src/java/biblioteca/acervo/InserirAcervo.java
  app/src/java/biblioteca/acervo/Validacao.java
  app/web/WEB-INF/lib/activation.jar
  app/web/WEB-INF/lib/commons-email-1.3.jar
  app/web/WEB-INF/lib/mail.jar
  docs/estrutura/biblioteca/.delete
  docs/estrutura/biblioteca/Acervo.md
Labels: enhancement

#74 Corrigindo erros relacionados à cpf
  app/src/java/diario/alunos/repository/AlunosRepository.java
Labels: fix

#88 Fix Manutenção de campi
  app/src/java/diario/campi/repository/CampiRepository.java
  app/src/java/diario/campi/servlets/AlterarCampi.java
  app/src/java/diario/campi/servlets/ConsultarPorId.java
  app/src/java/diario/campi/servlets/DeletarCampi.java
  app/src/java/diario/campi/servlets/InserirCampi.java
  app/src/java/diario/campi/servlets/ListarCampi.java
Labels: fix

#86 Manutenção de alunos (biblioteca)
  app/src/java/biblioteca/alunos/repository/AlunosRepository.java
  app/src/java/biblioteca/alunos/servlets/Alterar.java
  app/src/java/biblioteca/alunos/servlets/Consultar.java
  app/src/java/biblioteca/alunos/servlets/Delet.java
  app/src/java/biblioteca/alunos/servlets/Inserir.java
  app/src/java/biblioteca/alunos/servlets/Listar.java
Labels: enhancement

#90 Manutenção de Campi (biblioteca)
  app/src/java/biblioteca/campi/repository/CampiRepository.java
  app/src/java/biblioteca/campi/servlets/AlterarCampus.java
  app/src/java/biblioteca/campi/servlets/ConsultarCampus.java
  app/src/java/biblioteca/campi/servlets/DeletarCampus.java
  app/src/java/biblioteca/campi/servlets/InserirCampus.java
  app/src/java/biblioteca/campi/servlets/ListarCampus.java
Labels: enhancement

#80 Aprimoramento da manutenção de departamentos
  app/src/java/diario/departamentos/controller/Atualiza.java
  app/src/java/diario/departamentos/controller/AutenticacaoException.java
  app/src/java/diario/departamentos/controller/Consulta.java
  app/src/java/diario/departamentos/controller/Insere.java
  app/src/java/diario/departamentos/controller/ParametrosIncorretosException.java
  app/src/java/diario/departamentos/controller/Remove.java
  app/src/java/diario/departamentos/model/DepartamentoValidation.java
  app/src/java/diario/departamentos/repository/DepartamentoInexistenteException.java
  app/src/java/diario/departamentos/repository/DepartamentoRepository.java
  app/src/java/diario/departamentos/view/ConsultaView.java
  app/src/java/diario/departamentos/view/DepartamentosView.java
  app/src/java/diario/departamentos/view/ErroView.java
  app/src/java/diario/departamentos/view/RenderException.java
  app/src/java/diario/departamentos/view/SucessoView.java
  app/src/java/diario/departamentos/view/View.java
Labels: enhancement

#102 Correcoes nas pesquisas ao bd
  app/src/java/diario/departamentos/model/Departamento.java
  app/src/java/diario/departamentos/repository/DepartamentoRepository.java
  app/src/java/diario/departamentos/view/DepartamentosView.java
Labels: fix

#103 Validando CPF (diário e biblioteca)
  app/src/java/biblioteca/alunos/repository/AlunosRepository.java
  app/src/java/biblioteca/alunos/servlets/Inserir.java
  app/src/java/diario/alunos/repository/AlunosRepository.java
  app/src/java/diario/alunos/servlets/InserirAlunos.java
  app/src/java/utils/Validators.java
Labels: enhancement

#105 Pequenas melhoras
  app/nbproject/project.properties
  app/nbproject/project.xml
  app/src/java/biblioteca/acervo/AtualizarAcervo.java
  app/src/java/biblioteca/acervo/Validacao.java
Labels: enhancement

#104 Relatório 8 e 9
  app/src/java/diario/relatorios/relatorio8/AlunosConexao.java
  app/src/java/diario/relatorios/relatorio9/Rel9.java
  app/src/java/diario/relatorios/relatorio9/XmlProf.java
Labels: enhancement

#112 Atualizações e correções na documentação
  README.md
  TO-DO.md
Labels: enhancement, fix
